config/routes.rb
Rails.application.routes.draw do
  resources :store_assistants
  resources :shop_stores
  root 'welcome#index'
  resources :admins do
    get :confirm, on: :member
    get :deny, on: :member
  end
  resources :events do
    get :reset_count, on: :collection
  end
  resources :tests do
    get :test2, on: :collection
    get :test3, on: :collection
    get :test4, on: :collection
    get :test5, on: :collection
    get :test6, on: :collection
  end
  resources :quests do
    get :quest2, on: :collection
    get :quest3, on: :collection
    get :quest4, on: :collection
    get :quest5, on: :collection
    get :quest6, on: :collection
    get :quest7, on: :collection
    get :quest8, on: :collection
    get :quest9, on: :collection
    get :quest10, on: :collection
  end
  resources :shop_stores
  resources :store_assistants
  resources :users do
    resources :scanlogs
    get :userbinding, on: :collection
    get :userscore, on: :collection
    get :sns_oauth2, on: :collection
    get :sns_userinfo, on: :collection
    get :ticket, on: :collection
    get :token, on: :collection
    get :finduser, on: :collection
    get :userdetail, on: :collection
    get :modifyuser, on: :collection
  end
  resources :serials do
    get :scan, on: :collection
    get :build_serial, on: :collection
    get :multi_create, on: :collection
    get :single_create, on: :collection
    get :query, on: :collection
    patch 'create_multiple', :on => :member
    patch 'create_single', :on => :member
    patch 'download', :on => :member
  end
  resources :records do
    post :weixin, on: :collection
    get :receive, on: :member
  end
  resources :products do

    resources :extentions
    resources :serials do
      get :scan, on: :collection
      get :build_serial, on: :collection
      get :scan, on: :member
      get :unable, on: :member
    end
  end
  resources :orders
  resources :thirdparties
  resources :prizes
  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'

  resources :reports do
    get :idx1_1, on: :collection
    get :idx1_2, on: :collection
    get :idx1_3, on: :collection
    get :idx1_4, on: :collection
    get :idx1_5, on: :collection
    get :idx1_6, on: :collection

    get :idx2_1, on: :collection
    get :idx2_2, on: :collection
    get :idx2_3, on: :collection

    get :idx3_1, on: :collection
    get :idx3_2, on: :collection
    get :idx3_3, on: :collection
    get :idx3_4, on: :collection
    get :idx3_5, on: :collection
    get :idx3_6, on: :collection
    get :idx3_7, on: :collection

    get :idx4_1, on: :collection
    get :idx4_2, on: :collection
    get :idx4_3, on: :collection

    get :idx5_1, on: :collection
    get :idx5_2, on: :collection
    get :idx5_3, on: :collection

    get :idx6_1, on: :collection
    get :idx6_2, on: :collection

    get :idx7_1, on: :collection
    get :idx7_2, on: :collection
    get :idx7_3, on: :collection

    get :idx8_1, on: :collection
    get :idx8_2, on: :collection
  end

  namespace :api do
    resources :users, only: [:create, :update, :show, :send_code], defaults: {format: :json} do
      post :send_code, on: :collection
    end
    resources :serials, only: [:show, :confirm_action], defaults: {format: :json} do
      post :confirm_action, on: :collection
    end
    resources :events do
      post :record, on: :collection
    end
    resources :tests do
      post :submit, on: :collection
    end
    resources :quests do
      post :submit, on: :collection
    end
  end
end

app/models/shop_store.rb
class ShopStore < ActiveRecord::Base
  has_many :orders, dependent: :destroy
end

app/controllers/shop_stores_controller.rb
class ShopStoresController < ApplicationController
  before_action :set_shop_store, only: [:show, :edit, :update, :destroy]

  # GET /shop_stores
  # GET /shop_stores.json
  def index
    @shop_stores = ShopStore.all
  end

  # GET /shop_stores/1
  # GET /shop_stores/1.json
  def show
  end

  # GET /shop_stores/new
  def new
    @shop_store = ShopStore.new
  end

  # GET /shop_stores/1/edit
  def edit
  end

  # POST /shop_stores
  # POST /shop_stores.json
  def create
    @shop_store = ShopStore.new(shop_store_params)

    respond_to do |format|
      if @shop_store.save
        format.html { redirect_to @shop_store, notice: 'Shop store was successfully created.' }
        format.json { render :show, status: :created, location: @shop_store }
      else
        format.html { render :new }
        format.json { render json: @shop_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shop_stores/1
  # PATCH/PUT /shop_stores/1.json
  def update
    respond_to do |format|
      if @shop_store.update(shop_store_params)
        format.html { redirect_to @shop_store, notice: 'Shop store was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop_store }
      else
        format.html { render :edit }
        format.json { render json: @shop_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shop_stores/1
  # DELETE /shop_stores/1.json
  def destroy
    @shop_store.destroy
    respond_to do |format|
      format.html { redirect_to shop_stores_url, notice: 'Shop store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop_store
      @shop_store = ShopStore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_store_params
      params.require(:shop_store).permit(:title, :code, :contact, :mobile, :address)
    end
end

app/helpers/shop_store_helper.rb
module ShopStoreHelper
end

app/helpers/shop_stores_helper.rb
module ShopStoresHelper
end

app/views/shop_stores/_form.html.haml
= form_for @shop_store do |f|
  - if @shop_store.errors.any?
    #error_explanation
      %h2= "#{pluralize(@shop_store.errors.count, "error")} prohibited this shop_store from being saved:"
      %ul
        - @shop_store.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :code
    = f.text_field :code, class: 'form-control'
  .form-group
    = f.label :contact
    = f.text_field :contact, class: 'form-control'
  .form-group
    = f.label :mobile
    = f.text_field :mobile, class: 'form-control'
  .form-group
    = f.label :address
    = f.text_field :address, class: 'form-control'
  .actions
    = f.submit I18n.t('save'), class: 'btn btn-primary'

app/views/shop_stores/edit.html.haml
.content
  .row
    .box.box-primary
      .box-header.with-border
        %h1
          = t(:edit_shop_store)
      .box-body
        = render 'form'
      .box-footer
        = link_to t(:show), @shop_store
        \|
        = link_to t(:back), shop_stores_path

app/views/shop_stores/index.html.haml
%section.content-header
  %h1 
    =t(:shop_store_list)
%section.content
  .row
    .col-md-12
      .box
        .box-body
          %table.table.table-bordered
            %thead
              %tr
                %th 
                  =ShopStore.human_attribute_name(:title)
                %th
                  =ShopStore.human_attribute_name(:code) 
                %th
                  =ShopStore.human_attribute_name(:contact) 
                %th
                  =ShopStore.human_attribute_name(:mobile) 
                %th
                  =ShopStore.human_attribute_name(:address) 
                %th


            %tbody
              - @shop_stores.each do |shop_store|
                %tr
                  %td= shop_store.title
                  %td= shop_store.code
                  %td= shop_store.contact
                  %td= shop_store.mobile
                  %td= shop_store.address
                  %td
                    = link_to t('show'), shop_store, class: 'btn btn-info'
                    
                    = link_to t('edit'), edit_shop_store_path(shop_store), class: 'btn btn-warning'
                    
                    = link_to t('destroy'), shop_store, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

          %br
        .box-footer
          = link_to t(:new_shop_store), new_shop_store_path, class: 'btn btn-primary'

app/views/shop_stores/new.html.haml
.content
  .row
    .box.box-primary
      .box-header.with-border
        %h1
          = t(:new_shop_store)
      .box-body
        = render 'form'
      .box-footer
        = link_to t(:back), shop_stores_path

app/views/shop_stores/show.html.haml
.content
  .row
    .box.box-primary
      .box-header.with-border
        %h1
          = t(:show_shop_store)
      .box-body
        %p
          %label= ShopStore.human_attribute_name(:title) + ":"
          = @shop_store.title
        %p
          %label= ShopStore.human_attribute_name(:code)+ ":"
          = @shop_store.code
        %p
          %label= ShopStore.human_attribute_name(:contact)+ ":"
          = @shop_store.contact
        %p
          %label= ShopStore.human_attribute_name(:mobile)+ ":"
          = @shop_store.mobile
        %p
          %label= ShopStore.human_attribute_name(:address)+ ":"
          = @shop_store.address
      .box-footer
        = link_to I18n.t('edit'), edit_shop_store_path(@shop_store), class: 'btn btn-primary'
        
        = link_to I18n.t('back'), shop_stores_path, class: 'btn btn-info'