config/routes.rb
Rails.application.routes.draw do
  resources :store_assistants
  resources :shop_stores
  root 'welcome#index'
  resources :admins do
    get :confirm, on: :member
    get :deny, on: :member
  end
  resources :events do
    get :reset_count, on: :collection
  end
  resources :tests do
    get :test2, on: :collection
    get :test3, on: :collection
    get :test4, on: :collection
    get :test5, on: :collection
    get :test6, on: :collection
  end
  resources :quests do
    get :quest2, on: :collection
    get :quest3, on: :collection
    get :quest4, on: :collection
    get :quest5, on: :collection
    get :quest6, on: :collection
    get :quest7, on: :collection
    get :quest8, on: :collection
    get :quest9, on: :collection
    get :quest10, on: :collection
  end
  resources :shop_stores
  resources :store_assistants
  resources :users do
    resources :scanlogs
    get :userbinding, on: :collection
    get :userscore, on: :collection
    get :sns_oauth2, on: :collection
    get :sns_userinfo, on: :collection
    get :ticket, on: :collection
    get :token, on: :collection
    get :finduser, on: :collection
    get :userdetail, on: :collection
    get :modifyuser, on: :collection
  end
  resources :serials do
    get :scan, on: :collection
    get :build_serial, on: :collection
    get :multi_create, on: :collection
    get :single_create, on: :collection
    get :query, on: :collection
    patch 'create_multiple', :on => :member
    patch 'create_single', :on => :member
    patch 'download', :on => :member
  end
  resources :records do
    post :weixin, on: :collection
    get :receive, on: :member
  end
  resources :products do

    resources :extentions
    resources :serials do
      get :scan, on: :collection
      get :build_serial, on: :collection
      get :scan, on: :member
      get :unable, on: :member
    end
  end
  resources :orders
  resources :thirdparties
  resources :prizes
  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'

  resources :reports do
    get :idx1_1, on: :collection
    get :idx1_2, on: :collection
    get :idx1_3, on: :collection
    get :idx1_4, on: :collection
    get :idx1_5, on: :collection
    get :idx1_6, on: :collection

    get :idx2_1, on: :collection
    get :idx2_2, on: :collection
    get :idx2_3, on: :collection

    get :idx3_1, on: :collection
    get :idx3_2, on: :collection
    get :idx3_3, on: :collection
    get :idx3_4, on: :collection
    get :idx3_5, on: :collection
    get :idx3_6, on: :collection
    get :idx3_7, on: :collection

    get :idx4_1, on: :collection
    get :idx4_2, on: :collection
    get :idx4_3, on: :collection

    get :idx5_1, on: :collection
    get :idx5_2, on: :collection
    get :idx5_3, on: :collection

    get :idx6_1, on: :collection
    get :idx6_2, on: :collection

    get :idx7_1, on: :collection
    get :idx7_2, on: :collection
    get :idx7_3, on: :collection

    get :idx8_1, on: :collection
    get :idx8_2, on: :collection
  end

  namespace :api do
    resources :users, only: [:create, :update, :show, :send_code], defaults: {format: :json} do
      post :send_code, on: :collection
    end
    resources :serials, only: [:show, :confirm_action], defaults: {format: :json} do
      post :confirm_action, on: :collection
    end
    resources :events do
      post :record, on: :collection
    end
    resources :tests do
      post :submit, on: :collection
    end
    resources :quests do
      post :submit, on: :collection
    end
  end
end

app/views/admins/_form.html.haml
.row-fluid
  .col-md-6.col-md-offset-3
    .panel.panel-primary
      .panel-heading
        %h4.panel-title.text-center 用户
      = simple_form_for(@admin, html: { class: 'form-horizontal' }, |
        wrapper: :horizontal_form,                                  |
        wrapper_mappings: {                                         |
        check_boxes: :horizontal_radio_and_checkboxes,              |
        radio_buttons: :horizontal_radio_and_checkboxes,            |
        file: :horizontal_file_input,                               |
        boolean: :horizontal_boolean}) do |f|                       |
        .panel-body
          = f.input :name
          = f.input :address
          = f.input :cell
          = f.input :contact
          = f.input :email
          = f.input :website
          = f.input :password
          = f.input :password_confirmation
          = f.input :role, collection: [["第三方认证机构", "thirdparty"], ["管理员", "admin"]], :include_blank => false
        .panel-footer.text-center
          / <p class="text-center">
          = f.button :submit, class: "btn btn-danger"
          = link_to t(:back), :back, class: "btn btn-default"
          / </p>

app/views/admins/_form_new.html.haml
.register-box
  .register-logo
    %h4.panel-title.text-center 用户注册
  .register-box-body
    = simple_form_for(@admin, html: { class: 'form-horizontal' },wrapper: :horizontal_form,wrapper_mappings: {check_boxes: :horizontal_radio_and_checkboxes,radio_buttons: :horizontal_radio_and_checkboxes,file: :horizontal_file_input,boolean: :horizontal_boolean}) do |f| 
      .login-box-msg 
        
      .form-group.has-feedback
        %input.form-control.required{ type: :text, name: 'admin[name]', id: 'admin_name', placeholder: "企业名称" }
        %span.glyphicon.glyphicon-user.form-control-feedback
      .form-group.has-feedback
        %input.form-control.required{ type: :text, name: 'admin[email]', id: 'admin_email', placeholder: "email" }
        %span.glyphicon.glyphicon-user.form-control-feedback      
      .form-group.has-feedback
        %input.form-control.required{ type: :text, name: 'admin[cell]', id: 'admin_cell', placeholder: "手机号码" }
        %span.glyphicon.glyphicon-phone.form-control-feedback
      .form-group.has-feedback
        %input.form-control.required{ type: :text, name: 'admin[password]', id: 'admin_password', placeholder: "登录密码" }
        %span.glyphicon.glyphicon-lock.form-control-feedback
      .form-group.has-feedback
        %input.form-control.required{ type: :text, name: 'admin[password_confirmation]', id: 'admin_password_confirmation', placeholder: "确认密码" }
        %span.glyphicon.glyphicon-lock.form-control-feedback
      .form-group.has-feedback
        %input.form-control{ type: :text, name: 'admin[address]', id: 'admin_address', placeholder: "企业地址" }
        %span.glyphicon.glyphicon-home.form-control-feedback        
      .form-group.has-feedback
        %input.form-control{ type: :text, name: 'admin[contact]', id: 'admin_contact', placeholder: "联系方式" }
        %span.glyphicon.glyphicon-earphone.form-control-feedback
      .form-group.has-feedback
        %input.form-control{ type: :text, name: 'admin[website]', id: 'admin_website', placeholder: "企业网址" }
        %span.glyphicon.glyphicon-globe.form-control-feedback
      .row
        %input.btn.btn-primary.btn-block.btn-flat{type: :submit}          
        

app/views/admins/_form_update.html.haml
.row-fluid
  .col-md-6.col-md-offset-3
    .panel.panel-primary
      .panel-heading
        %h4.panel-title.text-center 用户
      = simple_form_for(@admin, html: { class: 'form-horizontal' }, |
        wrapper: :horizontal_form,                                  |
        wrapper_mappings: {                                         |
        check_boxes: :horizontal_radio_and_checkboxes,              |
        radio_buttons: :horizontal_radio_and_checkboxes,            |
        file: :horizontal_file_input,                               |
        boolean: :horizontal_boolean}) do |f|                       |
        .panel-body
          = f.input :password
          = f.input :password_confirmation
        .panel-footer.text-center
          / <p class="text-center">
          = f.button :submit, class: "btn btn-danger"
          = link_to t(:back), :back, class: "btn btn-default"
          / </p>

app/views/admins/edit.html.haml
= render 'form_update'

app/views/admins/index.html.haml
.row-fluid
  .col-md-12
    .panel.panel-danger
      / Default panel contents
      .panel-heading
        %h4.panel-title.text-center= t(:admin_list)
      %table.table.table-bordered.table-hover
        %thead
          %tr
            %th #
            %th= Admin.human_attribute_name("name")
            %th= Admin.human_attribute_name("email")
            %th= Admin.human_attribute_name("state")
            %th{:colspan => "4"}= t(:operations)
        %tbody
          - @admins.each do |admin|
            %tr
              %td= admin.id
              %td= admin.name
              %td= admin.email
              %td= admin.state
              %td= link_to t(:confirm), confirm_admin_path(admin) if can? :confirm, Admin
              %td= link_to t(:deny), deny_admin_path(admin) if can? :deny, Admin
              %td= link_to t(:reset_password), edit_admin_path(admin) if can? :update, admin
              %td= link_to t(:destroy), admin, method: :delete, data: {confirm: t(:are_you_sure)} if can? :delete, Admin
.row-fluid
  .col-md-4
    = link_to t(:new_admin), new_admin_path, class: "btn btn-danger"

app/views/admins/new.html.haml
- if current_user && (current_user.role == "admin")
  = render 'form'
- else
  = render 'form_new'