config/routes.rb
Rails.application.routes.draw do
  resources :store_assistants
  resources :shop_stores
  root 'welcome#index'
  resources :admins do
    get :confirm, on: :member
    get :deny, on: :member
  end
  resources :events do
    get :reset_count, on: :collection
  end
  resources :tests do
    get :test2, on: :collection
    get :test3, on: :collection
    get :test4, on: :collection
    get :test5, on: :collection
    get :test6, on: :collection
  end
  resources :quests do
    get :quest2, on: :collection
    get :quest3, on: :collection
    get :quest4, on: :collection
    get :quest5, on: :collection
    get :quest6, on: :collection
    get :quest7, on: :collection
    get :quest8, on: :collection
    get :quest9, on: :collection
    get :quest10, on: :collection
  end
  resources :shop_stores
  resources :store_assistants
  resources :users do
    resources :scanlogs
    get :userbinding, on: :collection
    get :userscore, on: :collection
    get :sns_oauth2, on: :collection
    get :sns_userinfo, on: :collection
    get :ticket, on: :collection
    get :token, on: :collection
    get :finduser, on: :collection
    get :userdetail, on: :collection
    get :modifyuser, on: :collection
  end
  resources :serials do
    get :scan, on: :collection
    get :build_serial, on: :collection
    get :multi_create, on: :collection
    get :single_create, on: :collection
    get :query, on: :collection
    patch 'create_multiple', :on => :member
    patch 'create_single', :on => :member
    patch 'download', :on => :member
  end
  resources :records do
    post :weixin, on: :collection
    get :receive, on: :member
  end
  resources :products do

    resources :extentions
    resources :serials do
      get :scan, on: :collection
      get :build_serial, on: :collection
      get :scan, on: :member
      get :unable, on: :member
    end
  end
  resources :orders
  resources :thirdparties
  resources :prizes
  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'

  resources :reports do
    get :idx1_1, on: :collection
    get :idx1_2, on: :collection
    get :idx1_3, on: :collection
    get :idx1_4, on: :collection
    get :idx1_5, on: :collection
    get :idx1_6, on: :collection

    get :idx2_1, on: :collection
    get :idx2_2, on: :collection
    get :idx2_3, on: :collection

    get :idx3_1, on: :collection
    get :idx3_2, on: :collection
    get :idx3_3, on: :collection
    get :idx3_4, on: :collection
    get :idx3_5, on: :collection
    get :idx3_6, on: :collection
    get :idx3_7, on: :collection

    get :idx4_1, on: :collection
    get :idx4_2, on: :collection
    get :idx4_3, on: :collection

    get :idx5_1, on: :collection
    get :idx5_2, on: :collection
    get :idx5_3, on: :collection

    get :idx6_1, on: :collection
    get :idx6_2, on: :collection

    get :idx7_1, on: :collection
    get :idx7_2, on: :collection
    get :idx7_3, on: :collection

    get :idx8_1, on: :collection
    get :idx8_2, on: :collection
  end

  namespace :api do
    resources :users, only: [:create, :update, :show, :send_code], defaults: {format: :json} do
      post :send_code, on: :collection
    end
    resources :serials, only: [:show, :confirm_action], defaults: {format: :json} do
      post :confirm_action, on: :collection
    end
    resources :events do
      post :record, on: :collection
    end
    resources :tests do
      post :submit, on: :collection
    end
    resources :quests do
      post :submit, on: :collection
    end
  end
end

app/models/record.rb
class Record < ActiveRecord::Base
  ITEMS = ["free_charge", "fifty_discount", "thirty_discount", "ten_discount", "red_envelop"]
  belongs_to :user
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  skip_before_action :logged_in_admin, only: [:weixin]
  def weixin
    user = User.find_by(openid: params[:record][:openid])
    
    return render json: {message: "谢谢参与", code: nil} if user.nil? # no user found
    
    return render json: {message: "谢谢参与", code: nil} if user.state == 1 # no user found

    user.update(cell: params[:record][:cell], state: 1)
    prize_city = Prize.find_by(city: params[:record][:city])
    
    return render json: {message: "谢谢参与", code: nil} if prize_city.nil? # can not find city

    item = Record::ITEMS.sample
    balance = prize_city.send(item) - Record.where(city: params[:record][:city], prize: Prize.human_attribute_name(item)).count
    return render json: {message: "谢谢参与", code: nil} if balance <= 0  # no balance in this item

    if rand((1/prize_city.send("#{item}_ratio")).to_i) == rand((1/prize_city.send("#{item}_ratio")).to_i)
      record = Record.create(
        city: params[:record][:city],
        prize: Prize.human_attribute_name(item),
        user_id: user.id,
        code: rand(100000..999999),
        state: '未领取')
      return render json: {message: record.prize, code: record.code}, status: 201
    else
      return render json: {message: "谢谢参与", code: nil}
    end
  end

  def index
    @q = Record.ransack(params[:q])
    @records = @q.result.page(params[:page])
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)
    if @record.save
      redirect_to records_url
    else
      render 'new'
    end
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])
    if @record.update(record_params)
      redirect_to records_url
    else
      render 'edit'
    end
  end

  def destroy
    Record.find(params[:id]).destroy
    redirect_to records_url
  end

  def receive
    Record.find(params[:id]).update(state: "已领取")
    redirect_to records_url
  end

  private
    def record_params
      params.require(:record).permit(:user_id, :city, :prize, :code)
    end
end

app/views/records/_form.html.haml
.col-md-6
  = simple_form_for(@record, html: { class: 'form-horizontal' }, |
    wrapper: :horizontal_form,                                   |
    wrapper_mappings: {                                          |
    check_boxes: :horizontal_radio_and_checkboxes,               |
    radio_buttons: :horizontal_radio_and_checkboxes,             |
    file: :horizontal_file_input,                                |
    boolean: :horizontal_boolean}) do |f|                        |
    = f.input :user_id, collection: User.all
    = f.input :city
    = f.input :prize
    = f.input :code
    = f.button :submit
.col-md-12
  = link_to t(:back), :back

app/views/records/_record.html.haml
%tr
  %td= record.user.cell if record.user
  %td= Rumoji.decode(record.user.name) if record.user
  %td= record.city
  %td= record.prize
  %td= record.code
  %td= record.state
  %td= record.created_at.to_s(:db)
  %td= record.updated_at.to_s(:db)
  %td= link_to t(:receive), receive_record_path(record)
  %td= link_to t(:edit), edit_record_path(record)
  %td= link_to t(:destroy), record, method: :delete, data: {confirm: t(:are_you_sure)}

app/views/records/_search.html.haml
= search_form_for(@q, html: { class: 'form-horizontal' }, |
  wrapper: :horizontal_form,                              |
  wrapper_mappings: {                                     |
  check_boxes: :horizontal_radio_and_checkboxes,          |
  radio_buttons: :horizontal_radio_and_checkboxes,        |
  file: :horizontal_file_input,                           |
  boolean: :horizontal_boolean}) do |f|                   |
  .col-md-3
    = f.input :user_name_cont, required: false, label: User.human_attribute_name('name')
  .col-md-3
    = f.input :user_cell_cont, required: false, label: User.human_attribute_name('cell')
  .col-md-3
    = f.input :city_eq, required: false, collection: Record.pluck(:city).uniq, label: Record.human_attribute_name('city')
  .col-md-3
    = f.input :prize_eq, required: false, collection: Record.pluck(:prize).uniq, label: Record.human_attribute_name('prize')
  .col-md-3
    = f.input :state_eq, required: false, collection: Record.pluck(:state).uniq, label: Record.human_attribute_name('state')
  .col-md-3
    = f.button :submit, t(:search)

app/views/records/edit.html.haml
= render 'form'

app/views/records/index.html.haml
.col-md-10
  %h3= t(:record_list)
.col-md-2
  = link_to t("new_record"), new_record_path, class: "btn btn-danger"
.col-md-12
  = render 'search'
.col-md-12
  = paginate @records
  %table.table
    %thead
      %tr
        %th= sort_link(@q, :user_cell, User.human_attribute_name(:cell))
        %th= sort_link(@q, :user_name, User.human_attribute_name(:name))
        %th= sort_link(@q, :city, Record.human_attribute_name(:city))
        %th= sort_link(@q, :prize, Record.human_attribute_name(:prize))
        %th= sort_link(@q, :code, Record.human_attribute_name(:code))
        %th= sort_link(@q, :state, Record.human_attribute_name(:state))
        %th= sort_link(@q, :created_at, Record.human_attribute_name(:created_at))
        %th= sort_link(@q, :updated_at, Record.human_attribute_name(:updated_at))
        %th{:colspan => "3"}= t(:operations)
    %tbody
      = render @records
  = paginate @records

app/views/records/new.html.haml
= render 'form'