config/routes.rb
Rails.application.routes.draw do
  resources :store_assistants
  resources :shop_stores
  root 'welcome#index'
  resources :admins do
    get :confirm, on: :member
    get :deny, on: :member
  end
  resources :events do
    get :reset_count, on: :collection
  end
  resources :tests do
    get :test2, on: :collection
    get :test3, on: :collection
    get :test4, on: :collection
    get :test5, on: :collection
    get :test6, on: :collection
  end
  resources :quests do
    get :quest2, on: :collection
    get :quest3, on: :collection
    get :quest4, on: :collection
    get :quest5, on: :collection
    get :quest6, on: :collection
    get :quest7, on: :collection
    get :quest8, on: :collection
    get :quest9, on: :collection
    get :quest10, on: :collection
  end
  resources :shop_stores
  resources :store_assistants
  resources :users do
    resources :scanlogs
    get :userbinding, on: :collection
    get :userscore, on: :collection
    get :sns_oauth2, on: :collection
    get :sns_userinfo, on: :collection
    get :ticket, on: :collection
    get :token, on: :collection
    get :finduser, on: :collection
    get :userdetail, on: :collection
    get :modifyuser, on: :collection
  end
  resources :serials do
    get :scan, on: :collection
    get :build_serial, on: :collection
    get :multi_create, on: :collection
    get :single_create, on: :collection
    get :query, on: :collection
    patch 'create_multiple', :on => :member
    patch 'create_single', :on => :member
    patch 'download', :on => :member
  end
  resources :records do
    post :weixin, on: :collection
    get :receive, on: :member
  end
  resources :products do

    resources :extentions
    resources :serials do
      get :scan, on: :collection
      get :build_serial, on: :collection
      get :scan, on: :member
      get :unable, on: :member
    end
  end
  resources :orders
  resources :thirdparties
  resources :prizes
  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'

  resources :reports do
    get :idx1_1, on: :collection
    get :idx1_2, on: :collection
    get :idx1_3, on: :collection
    get :idx1_4, on: :collection
    get :idx1_5, on: :collection
    get :idx1_6, on: :collection

    get :idx2_1, on: :collection
    get :idx2_2, on: :collection
    get :idx2_3, on: :collection

    get :idx3_1, on: :collection
    get :idx3_2, on: :collection
    get :idx3_3, on: :collection
    get :idx3_4, on: :collection
    get :idx3_5, on: :collection
    get :idx3_6, on: :collection
    get :idx3_7, on: :collection

    get :idx4_1, on: :collection
    get :idx4_2, on: :collection
    get :idx4_3, on: :collection

    get :idx5_1, on: :collection
    get :idx5_2, on: :collection
    get :idx5_3, on: :collection

    get :idx6_1, on: :collection
    get :idx6_2, on: :collection

    get :idx7_1, on: :collection
    get :idx7_2, on: :collection
    get :idx7_3, on: :collection

    get :idx8_1, on: :collection
    get :idx8_2, on: :collection
  end

  namespace :api do
    resources :users, only: [:create, :update, :show, :send_code], defaults: {format: :json} do
      post :send_code, on: :collection
    end
    resources :serials, only: [:show, :confirm_action], defaults: {format: :json} do
      post :confirm_action, on: :collection
    end
    resources :events do
      post :record, on: :collection
    end
    resources :tests do
      post :submit, on: :collection
    end
    resources :quests do
      post :submit, on: :collection
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :admin
  has_many :extentions, dependent: :destroy
  has_many :serials, dependent: :destroy
  mount_uploader :product_image, ImageUploader
  mount_uploader :product_logo, ImageUploader

  # accepts_nested_attributes_for :serials

  validates :product_name, presence: true
  validates :score, presence: true

  state_machine :state, :initial => :'正常' do
    event :deny do
      transition [:'正常'] => :'无效'
    end
  end
end

app/controllers/products_controller.rb
require 'rubygems'
require 'zip'
class ProductsController < ApplicationController
  load_and_authorize_resource

  def index
    @products = Product.where(:admin_id => current_user.id)
    @products_grid = initialize_grid(
      Product.where(admin_id: current_user.id),
      name: 'products_grid')
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
    @serials_grid = initialize_grid(Serial.where(product_id: @product.id),
                    name:'serials')

    if params[:serials] && params[:serials][:selected]
      folder = "public/img/qrcode"
      input_filenames = []
      @serials = Serial.where(id: params[:serials][:selected])
      @serials.each do |file|
        input_filenames.push(file.id.to_s + '.png')
      end

      #Attachment name
      filename = '二维码_'+Time.now.strftime('%Y%m%d').to_s+'_'+Time.now.to_i.to_s+'.zip'
      temp_file = Tempfile.new(filename)

      begin
        #This is the tricky part
        #Initialize the temp file as a zip file
        Zip::OutputStream.open(temp_file) { |zos| }

        #Add files to the zip file as usual
        Zip::File.open(temp_file.path, Zip::File::CREATE) do |zipfile|
          input_filenames.each do |filename|
            # Two arguments:
            # - The name of the file as it will appear in the archive
            # - The original file, including the path to find it
            zipfile.add(filename, folder + '/' + filename)
          end
          # zipfile.get_output_stream("myFile") { |os| os.write "myFile contains just this" }
        end

        #Read the binary data from the file
        zip_data = File.read(temp_file.path)

        #Send the data to the browser as an attachment
        #We do not send the file directly because it will
        #get deleted before rails actually starts sending it
        send_data(zip_data, :type => 'application/zip', :filename => filename)
      ensure
        #Close and delete the temp file
        temp_file.close
        temp_file.unlink
      end
    end
  end

  def create
    @product = Product.new(product_params)
    @product.admin_id = current_user.id
    if @product.save
      redirect_to edit_product_path(@product)
    else
      render 'new'
    end
  end

  def download

  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_url
    else
      render 'edit'
    end
  end

  def destroy
    Product.find(params[:id]).destroy
    redirect_to products_url
  end

  private
   def product_params
    params.require(:product).permit(
      :product_name, :product_image, :admin_id, :how_many, :score, :product_logo, :desc)
   end
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/views/products/_form.html.haml
.row-fluid    
  .col-md-6.col-md-offset-3
    .panel.panel-primary
      .panel-heading
        %h4.panel-title.text-center= Product.model_name.human
      = simple_form_for(@product, html: { class: 'form-horizontal' }, |
        wrapper: :horizontal_form,                                    |
        wrapper_mappings: {                                           |
        check_boxes: :horizontal_radio_and_checkboxes,                |
        radio_buttons: :horizontal_radio_and_checkboxes,              |
        file: :horizontal_file_input,                                 |
        boolean: :horizontal_boolean}) do |f|                         |
        .panel-body
          = f.input :product_name
          = f.input :product_logo
          = f.input :product_image
          = f.input :score
          /
            <label class="control-label">Select File</label>
            <input id="input-1" type="file" class="file">
        .panel-footer.text-center
          / <p class="text-center">
          = f.button :submit, class: "btn btn-danger"
          - if !@product.id.nil?
            = link_to "预览", "#", data: {toggle: "modal", target: "#myModal#{@product.id}"}, class: "btn btn-primary"
          = link_to t(:back), products_path, class: "btn btn-default"
          / </p>

app/views/products/_form_extend.html.haml
.row-fluid
  .col-md-6.col-md-offset-3
    .panel.panel-primary
      .panel-heading
        %h4.panel-title.text-center= Extention.model_name.human
      = simple_form_for([@product, @product.extentions.build], html: { class: 'form-horizontal' }, |
        wrapper: :horizontal_form,                                                                 |
        wrapper_mappings: {                                                                        |
        check_boxes: :horizontal_radio_and_checkboxes,                                             |
        radio_buttons: :horizontal_radio_and_checkboxes,                                           |
        file: :horizontal_file_input,                                                              |
        boolean: :horizontal_boolean}) do |f|                                                      |
        .panel-body
          = f.input :extention_name
          = f.input :extention_type
        .panel-footer.text-center
          / <p class="text-center">
          = f.button :submit, class: "btn btn-danger"
          = link_to t(:back), :back, class: "btn btn-default"
          / </p>

app/views/products/_grid.html.erb
<%= define_grid(@products_grid) do |g|

  g.blank_slate  do
	  "没有记录"
	end

  g.column :name => '#', :attribute => 'id', filter: false

  g.column :name => Product.human_attribute_name(:product_name), :attribute => 'product_name', detach_with_id: :name_filter

  g.column :name => Product.human_attribute_name(:score), :attribute => 'score', detach_with_id: :score_filter

  g.column :name => Product.human_attribute_name(:product_logo), :attribute => 'product_logo', filter: false do |product|
    image_tag product.product_logo.thumb
  end

  g.column :name => Product.human_attribute_name(:product_image), :attribute => 'product_image', filter: false do |product|
    image_tag product.product_image.thumb
  end

  g.column :name => Product.human_attribute_name(:created_at), :attribute => 'created_at', filter: false do |product|
    product.created_at.strftime('%F')
  end

  g.column :name => Product.human_attribute_name(:updated_at), :attribute => 'updated_at', filter: false do |product|
    product.updated_at.strftime('%F')
  end

  g.column :name => '操作'  do |product|
    buffer =
    render 'products/modal', :product => product
    buffer += ' '
    buffer +=
    #if can? :read, Product
      link_to "预览", "#", data: {toggle: "modal", target: "#myModal#{product.id}"}, class: 'btn btn-info'
    #end
    buffer += ' '
    buffer +=
    #if can? :update, Product
      link_to t(:edit), edit_product_path(product), class: 'btn btn-warning'
    #end
    buffer += ' '
    buffer +=
    #if can? :destroy, Product
      link_to t(:destroy), product, method: :delete, data: {confirm: t(:are_you_sure)}, class: 'btn btn-danger'
    #end
    raw buffer
  end

end -%>

app/views/products/_modal.html.haml
.modal.fade{:id => "myModal#{product.id}", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-sm{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title.text-center 产品扫码-预览
      .modal-body{:style => "padding-left: 0px;padding-right: 0px;padding-top: 0px;padding-bottom: 0px;"}
        .page1{:style => "background-color: #1c1403; overflow: hidden;"}

          /
            <div class="underBlock fl">
            <img id="imgIntro"/>
            </div>
          .underBlock.fl.MT5.clearfix
            %img.bg{:src => "#{product.product_image}"}/
            / <img class="word" src="img/page1/page1_word.png">
            / <img class="head" src="img/page1/page1_head.png">
            / <img class="addr" src="img/page1/page1_addr.png">
            / <img class="logo" src="img/page1/page1_logo2.png">

app/views/products/edit.html.haml
%p= render 'form'
= render 'products/modal', :product => @product

app/views/products/index.html.haml
= render 'grid'
.row-fluid
  .col-md-12.well{:style => "margin-bottom: 0px;border-bottom-width: 0px;padding-bottom: 0px;border-radius: 0px;"}
    %form.form-horizontal.row{:role => "form"}
      .col-xs-4
        .form-group
          %label.col-sm-6.control-label{:for => "exampleInput1"}
            %span= Product.human_attribute_name(:product_name)
          .col-sm-6
            = grid_filter @products_grid, :name_filter
      .col-xs-4
        .form-group
          %label.col-sm-6.control-label{:for => "exampleInput2"}= Product.human_attribute_name(:score)
          .col-sm-6
            = grid_filter @products_grid, :score_filter
      .col-xs-4
        .external-buttons
          %button.btn.btn-primary.wg-external-submit-button{"data-grid-name" => "products_grid"} 查询
          = link_to t(:new_product), new_product_path, class: "btn btn-danger" 
  .row-fluid
    .col-md-12{:style => "padding-left: 0px;padding-right: 0px;"}
      = render_grid(@products_grid)
  

app/views/products/new.html.haml
%p= render 'form'

app/views/products/show.html.haml
/ <div class="row">
.row
  .col-md-6
    .panel.panel-info
      .panel-heading
        .panel-title.text-center
          %h4= @product.product_name
          %span
            = Product.human_attribute_name("score")
            ：
            \#{@product.score}
      .panel-body
        %p.text-center
          = image_tag @product.product_image.preview
      %table.table.table-striped
        %tbody
          = render @product.extentions
  .col-md-4.col-md-offset-2
    .panel.panel-info
      .panel-heading
        %h4.panel-title.text-center 产品维护
      .panel-body
        = simple_form_for([@product, @product.extentions.build]) do |f|
          / <div class="panel-body">
          = f.input :extention_name
          = f.input :extention_value, as: :text, input_html: {rows: 6}
          / </div>
          .text-center
            = f.button :submit, class: "btn btn-danger"
/ <div class="row">
.row
  .col-md-3
    = form_for @product, url: create_multiple_product_path(@product) do |f|
      .input-group
        = f.hidden_field :product_id, :value => @product.id
        = f.text_field :how_many, :label => false, :value => "", placeholder: "输入二维码数量", class: "form-control"
        / <input type="text" class="form-control" placeholder="Search for...">
        %span.input-group-btn
          = f.submit "提交", class: "btn btn-success"
  .col-md-9
.row
  /
    <div class="col-md-12">
    </br>
    <div class="panel panel-success">
    <div class="panel-heading">
    <h4 class="panel-title text-center">产品二维码</h4>
    </div>
    
    <table class="table table-striped">
    <tbody>
    render @product.serials
    </tbody>
    </table>
    </div>
    </div>
  = form_for '#', method:  :get do
    .col-md-12
      .panel.panel-primary
        .panel-heading
          %h4.panel-title.text-center 产品二维码
        %div
          = render :partial => 'serials/serials_grid'
          = render_grid(@serials_grid)
      %div
        %button.btn.btn-danger{:type => "submit"} 下载二维码
/ </div>
/ </div>